# SPDX-License-Identifier: GPL-2.0-only
#
# MI UnionPower core: frame load / jank monitor (built-in port)
#

obj-$(CONFIG_MI_UNION_POWER) += unionpower.o
unionpower-objs := unionpower_main.o frame_load_monitor.o union_power_ioctl.o
